services:
  tpv-eureka:
    build: .
    image: goa-eureka:1.0.0
    restart: always
    ports:
      - "8761:8761"
    networks:
      - goa

networks:
  goa:
    external: true

#> docker network create miw
#> docker compose up --build -d
