services:
  goa-eureka:
    container_name: goa-eureka
    build: .
    image: ghcr.io/miw-upm/goa-eureka:latest
    restart: always
    ports:
      - "8761:8761"
    networks:
      - goa

networks:
  goa:
    external: true

#> docker network create goa
#> docker compose up --build -d
