services:
  goa-eureka:
    build: .
    image: goa-eureka:1.0.0
    restart: always
    ports:
      - "8761:8761"
    networks:
      - goa

networks:
  goa:
    external: true

#> docker network create goa
#> docker compose -f docker-compose-dev.yml up --build -d
