name: CD. AWS Lightsail
on:
  push:
    branches:
      - staging

jobs:
  cd:
    name: Build & Push GitHub Package & Deploy on AWS Lightsail
    runs-on: ubuntu-22.04

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🏷️ Prepare container registry metadata (repository, artifact, version...)
        run: |
          echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV          
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: 📦 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: 🐳 Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPOSITORY }}:latest

      - name: 🚀 Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.AWS_LIGHTSAIL_IP_STAGING }}
          username: ${{ secrets.AWS_LIGHTSAIL_USER_STAGING }}
          key: ${{ secrets.AWS_LIGHTSAIL_SSH_KEY_STAGING }}
          script: |
            echo ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker rm -f ${{ env.ARTIFACT }} || true
            docker pull ghcr.io/${{ env.REPOSITORY }}:latest
            docker run -d \
              --name ${{ env.ARTIFACT }} \
              --restart always \
              --memory 512m \
              --memory-swap 1024m \
              --network goa \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_USER=${{ secrets.EUREKA_USER }} \
              -e EUREKA_PASSWORD=${{ secrets.EUREKA_PASSWORD }} \
              ghcr.io/${{ env.REPOSITORY }}:latest
            docker stop goa-gateway
            docker stop goa-engagement
            docker stop goa-user
            docker stop goa-support
            sleep 40
            docker stop goa-support
            docker start goa-user
            docker start goa-engagement            
            docker start goa-gateway
